# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration
AllCops:
  NewCops: enable
  Exclude:
    # be nice to lint these, but we need to work out how to ignore the
    # frontmatter parts at the top of the file which aren't valid ruby
    - source/**/*.builder

Style/Documentation:
  Enabled: false # eh... I don't wanna
Style/FrozenStringLiteralComment:
  Enabled: false # we're on ruby 3.4 so we don't need this
Style/MultilineBlockChain:
  Enabled: false # not buying the rationale on this one
Style/StringLiterals:
  EnforcedStyle: double_quotes # avoid git diff churn
# all these trailing comma ones help reduce git diff churn too
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented # the indent helps readability

# none of these metrics cops are interesting (imho)
Metrics:
  Enabled: false

Naming/VariableNumber:
  Enabled: false # no rationale + think the offence doesn't read better "fixed"
