on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Ruby Version
        run: |
          ruby -v

      - name: Rubocop Lint
        # yamllint disable rule:line-length
        run: |
          bundle exec rubocop --format progress --format RubocopGithubAnnotationFormatter::AnnotationFormatter
        # yamllint enable rule:line-length

      - name: Yaml Lint
        run: |
          pip install yamllint
          yamllint . --format github

      - name: Yaml Frontmatter Lint
        run: |
          bundle exec ruby ./lib/lint_frontmatter_yaml.rb

      - name: Middleman Build
        run: |
          export TERM=xterm
          bundle exec middleman build -e production --verbose
