on:
  workflow_call:
    inputs:
      persist-output:
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Ruby Version
        run: |
          ruby -v

      - name: Rubocop Lint
        # yamllint disable rule:line-length
        run: |
          bundle exec rubocop --format progress --format RubocopGithubAnnotationFormatter::AnnotationFormatter
        # yamllint enable rule:line-length

      - name: Yaml Lint
        run: |
          pip install yamllint
          yamllint . --format github

      - name: Yaml Frontmatter Lint
        run: |
          bundle exec ruby ./lib/lint_frontmatter_yaml.rb

      - name: Middleman Build
        run: |
          export TERM=xterm
          bundle exec middleman build -e production --verbose

      - name: Store build output
        uses: actions/upload-artifact@v7
        if: ${{ inputs.persist-output }}
        with:
          name: build-output
          path: public
          retention-days: 1
          include-hidden-files: true
